### ISSUE TITLE
HandsInteractionTrainScene Buttons are not pokeable (v62)

### ISSUE THREAD

**Issue by Pepn** [oculus-samples/Unity-StarterSamples#10]
Running Oculus Packages v62 and Samples v62

**Comment by AlexThiv** [comment]
Hi @Pepn, thanks for bringing this up. When I tested I was able to press the different buttons as expected. Can you provide us with more details on what is happening.
How did you build the project?
What device you are using?
And logs when running on device `adb logcat -s Unity`

Thanks
