### ISSUE TITLE
Wide Motion Mode doesn't work when using OpenXR

### ISSUE THREAD

**Issue by WikkidEdd** [oculus-samples/Unity-StarterSamples#16]
# Description
When switching to the OpenXR Plugin wide motion mode does not work.

Using the Oculus XR Plugin wide motion mode works as expected.

# Setup
Unity: 2021.3.36f1
Packages: Meta XR Core SDK v 62.0.0; OpenXR Plugin 1.10.0; XR Plugin Management 4.4.0
Device: Quest 3, OS version 63.0.0.399.366

# Repro
With no other modifications to the code or project configuration:
+ Open the HandsInteractionTrain Scene
+ Find the OVRCamera Rig and enable "Wide Motion Mode Hand Poses Enabled" and add the Body Tracking Support permissions
+ Save the scene
+ Build using Oculus > Samples > Build Starter Scene and deploy to device
+ Run the app and navigate to the HandsInteractionTrain Scene
+ Raise your hands so they are detected, then place your hands by your waist looking down, then move your hands around your back.
+ You should observe that the hands stay visible even though they are no longer visible from the device.
+ Back in Unity, install the OpenXR Plugin package
+ Under Project Settings > XR Plug-in Management switch Plug-in Provider to OpenXR
+ Build using Oculus > Samples > Build Starter Scene and deploy to device
+ Run the app and navigate to the HandsInteractionTrain Scene
+ Raise your hands so they are detected, then place your hands by your waist looking down, then move your hands around your back.
+ This time note that the hands will disappear as soon at the device can no longer see them

# Expected Results
Your hands should remain enabled even when the device can't see them when using Wide Motion Mode with the OpenXR plugin

# Actual Results
Wide motion mode does not work when running OpenXR

# Workarounds
The cause of this bug seems to be due to the missing OpenXR extension  `XR_META_hand_tracking_wide_motion_mode`. You can create a custom OpenXR feature (as mentioned in this issue #12)  which includes that extension and the call to Wide Motion Mode now works

**Comment by TheJackuz** [comment]
My issue is a little off topic but i think it is related.
I have a Unity project that uses the Scene API: it only loads the room and then i use a raycast to check what i'm pointing.
This project worked fine 2 month ago, but now the scene does not load.
The only errors i get are the following:
- this one in the Package Manager
![image](https://github.com/oculus-samples/Unity-StarterSamples/assets/67840565/f7544c84-d635-487e-bf09-332175c984cb)

- this one in the console
![image](https://github.com/oculus-samples/Unity-StarterSamples/assets/67840565/f6ec9910-1f97-4be6-91b2-d5b47ea4f65f)

It seems that it is a recent issue based on the reports in this GitHub.
Is it going to be fixed soon?

**Comment by WikkidEdd** [comment]
It does sound similar in that there is a missing extension (assuming you're using the Unity OpenXR plugin and not the Oculus XR plugin).

You can try the work around here and change the extension to the one that is missing (`XR_FB_spatial_entity_query`) https://github.com/oculus-samples/Unity-StarterSamples/issues/12#issuecomment-2050339474

**Comment by TheJackuz** [comment]
I am using Oculus XR plugin. Could it be a non-related issue?

**Comment by WikkidEdd** [comment]
In that case it sound unrelated. I would file a new issue for you problem

**Comment by WikkidEdd** [comment]
@AlexThiv great to see the fix for #15 make it into v66. Any update on when this one will be fixed? It's a similar fix of just adding an extra string to the OpenXrExtensionList.

**Comment by AlexThiv** [comment]
This is on track for v68.

**Comment by AlexThiv** [comment]
v68 has been released with the fix

**Comment by WikkidEdd** [comment]
Great, thanks for getting these fixed. It would be super helpful if these minor changes were also captured in the release notes.
