### ISSUE TITLE
Errors during the Build Starter Scene

### ISSUE THREAD

**Issue by BANDWBEAR** [oculus-samples/Unity-StarterSamples#2]
Hi, I am following the documentation on developer.oculus.com. 
Unfortunately I am receiving a bunch of errors after launching the **Oculus -> Samples ->  Build Starter Scene**

**Unity 2021.3.26f1 Apple Silicon**
The first error looks like this: 
> '[Oculus.VR]OVRManager' has an extra field 'expandMixedRealityCapturePropertySheet' of type 'System.Boolean' in the player and thus can't be serialized  (expected 'launchMultimodalHandsControllersOnStartup' of type 'System.Boolean')
> UnityEditor.BuildPipeline:BuildPlayer (UnityEditor.BuildPlayerOptions)
> OculusBuildSamples:Build (string,string[]) (at Assets/StarterSamples/Editor/BuildSamples.cs:183)
> OculusBuildSamples:BuildStartScene () (at Assets/StarterSamples/Editor/BuildSamples.cs:138)

<img width="1463" alt="image" src="https://github.com/oculus-samples/Unity-StarterSamples/assets/13421635/b43d96df-f98d-4c37-9ecf-5d3ad2a41ab1">

My apologies for bothering you, but please can you help me to find out the root cause?

**Comment by AlexThiv** [comment]
Hi @BANDWBEAR,
Thanks for raising this issue.

Did you switch the platform to Android before launching the build or were you still on Standalone? It seems like this is an issue that can happen when building for a different platform than the selected one.

Can you test this out:
Go to **File -> Build Settings**, select **Android** under platform and click **Switch platform** in bottom right.
Then try to build Starter Scene, **Oculus -> Samples -> Build Starter Scene**

This will fix your issue.
We will also work on a proper fix in a future release to avoid this issue.

**Comment by BANDWBEAR** [comment]
Thanks, that helped.
I  switched the platform, but then still got an error `Failed to read key AndroidDebugKey from store`. Fixed by creating new key in **Project Settings -> Player -> Publishing Settings**, I guess it worth to mention for other people like me who just started to learn VR + Unity and will receive the same error.
