### ISSUE TITLE
TextMeshPro not rendering with OVROverlayCanvas on Quest 3

### ISSUE THREAD

**Issue by angecroft** [oculus-samples/Unity-StarterSamples#20]
### Description:
I've tried to use OVROverlayCanvas in a Unity project with TextMeshPro, but the text elements that utilize this script aren't rendered on the Quest 3. This issue can be reproduced using the OVROverlayCanvas_Text sample scene.

### Steps to Reproduce:
- Open the OVROverlayCanvas_Text sample scene in Unity.
- Deploy the scene to a Quest 3 device.
- Observe that TextMeshPro text elements do not render. Only the two Canvas that doesn't use the OVROverlayCanvas render.

### Environment:
**Device:** Meta Quest 3 v67 & v68
**Unity Version:** 2022.3.36f1
**Meta XR Core SDK:** v67
**TextMeshPro Version:** 3.0.6
**Building on:** macOS 14.5 | M1 Pro, Intel

https://github.com/user-attachments/assets/f778e93d-0ff5-4dae-adc7-67961be44494

**Comment by AlexThiv** [comment]
@angecroft Thanks for rising this issue. There was a change on how the OVROverlayCanvas shader is setup and it was missed in this release. To fix the issue you can open the OVROverlayCanvas_Text scene. A new setting file will be created OVROverlayCanvasSettings
![image](https://github.com/user-attachments/assets/a52230ae-68c6-4734-adde-572b554ff408)

Then to have the settings value set to default you will need to click on a GameObject with the OVR Overlay Canvas script. Here is an example from that scene
![image](https://github.com/user-attachments/assets/5c54fbd1-b866-4332-93d3-ed5d63a0e65a)

Finally the settings will have the default value
![image](https://github.com/user-attachments/assets/03cb763f-a29d-40b8-bba7-abc11b7d2e88)

Now you can rebuild and test. Sorry for the inconvenience we will fix it in an upcoming release.

**Comment by angecroft** [comment]
Thank you for your advice; it worked. 
However, when I build only the OVROverlayCanvas_Text scene without including any other scenes (so it starts directly with this one), I still can't see any of the OVROverlayCanvas. I tested this to closely replicate the setup of my project, where I still can't see any text using OVROverlayCanvas.

Is there anything in the StartScene, like settings or something else, that could interfere with the OVROverlayCanvas_Text scene?

Thank you for your help

**Comment by angecroft** [comment]
Hi @AlexThiv 

Apologies for the follow-up, but I wanted to check if you had a chance to look into launching the OVROverlayCanvas_Text independently, without using the SceneManager.

Thanks for your time!

**Comment by AlexThiv** [comment]
Hi @angecroft,

Yes we just looked into it, it seems to be a timing issue where the canvas gets the wrong scaling in the first frame. We have a fix coming up in a future update.

As a momentary fix you can have the OVROverlayCanvas disabled on the first frame of the application and enable them on a later frame, or have a startup scene that would load the scene with the OVROverlayCanvas.

**Comment by AlexThiv** [comment]
Our latest v68 release contains the initial [fix suggested](https://github.com/oculus-samples/Unity-StarterSamples/issues/20?fbclid=IwZXh0bgNhZW0CMTEAAR2yt6t4FQFM4no7_I-MAstphk3kfixjO5GatVxzb92WZgxS02uIx_3XU7M_aem_ZsmUzpRYcOdKQcYUUIBwZw#issuecomment-2289952753) previously.
