### ISSUE TITLE
Multiple bugs with HandsInteractionTrainScene

### ISSUE THREAD

**Issue by Pvanderlaan89** [oculus-samples/Unity-StarterSamples#4]
I want to try the new Meta UPM packages and this examples repo and I encounter multiple issues with the HandsInteractionTrainScene.

Poke interactors (blue spheres) don't follow finger tips (only very occasionally the poke spheres get correctly updated to the finger tips) which makes it hard to press the buttons. 

Skybox and button highlight shader doesn't work with Stereo Rendering Instancing (as recommended by the Oculus Project Setup Tool)

Lightmaps are broken
![2024-01-03_14-57-50](https://github.com/oculus-samples/Unity-StarterSamples/assets/47057446/c9205004-1778-453b-a923-eb0ceaf45ed8)

I encounter these issues in a new Unity 2022.3.11f1 (Built-in render pipeline) project with Meta XR All-in-One SDK 60.0.0 .

**Comment by AlexThiv** [comment]
Hi @Pvanderlaan89,
I just want to make sure I understand how you tested this project. Did you clone this repository and then add Meta XR All-in-One SDK v60, to get all upm packages?

What was your process to build the application? Did you build the scene specifically using the Build settings menu or did you build through the Oculus->Samples-> Build Starter Scene menu?

I just tested this repository using 2022.3.11f1 and didn't encounter the issues mentioned (except the lighting) If you could elaborate on the exact steps you took to generate your build it might help us reproduce your issues.

For the lighting we are aware and we are making a fix in a future version. You can go in Windows -> Rendering -> Lighting and regenerate the lightmap.

**Comment by AlexThiv** [comment]
Lighting is now fix. If you still have issues with the hands interaction you can open a new issue with additional details.
