### ISSUE TITLE
[SceneManager] Desk prefab is upside down when rendering

### ISSUE THREAD

**Issue by TheJackuz** [oculus-samples/Unity-StarterSamples#6]
I'm trying the scene SceneManager. It loads successfully but with the desk prefab upside down.
I tried to rotate it when the event OnSceneModelLoadedSuccessfully is invoked but it seems like it resets its transform.
Is there a way to fix it?

**Comment by AlexThiv** [comment]
Hi @TheJackuz,
Do you have an image to illustrate what you mean by upside down?
What headset are you using and which version of the OS is installed Settings>System>Software Update?

I tested on Quest3 and the desk is in the right direction with the axis on top pointing in the right direction as well.
As a solution you could reorient a child inside the desk prefab, but obviously you shouldn't have to do that and it should load correctly.

**Comment by tdmowrer** [comment]
The "SceneManager" sample does not include a desk; but if you're adding a prefab for desk, note that +Z is up, as described here, under the "Anchor Pivots" section:
https://developer.oculus.com/documentation/unity/unity-scene-use-scene-anchors/#anchor-pivots
