### ISSUE TITLE
Issues with Scene API

### ISSUE THREAD

**Issue by Spphire** [oculus-samples/Unity-StarterSamples#7]
Hi, I'm using scene api in quest3. But scene api doesnt work in built apk, while does work in quest link.
Do you know the reason? Appreciate it!

**Comment by Spphire** [comment]
It does work on my quest2

**Comment by tdmowrer** [comment]
What doesn't work exactly, e.g., do you get an error? Which sample are you running?

It would help track down the issue if you could share a logcat capture as well.

**Comment by WangMinan** [comment]
> What doesn't work exactly, e.g., do you get an error? Which sample are you running?
> 
> It would help track down the issue if you could share a logcat capture as well.

After factory settings, it works!

**Comment by Spphire** [comment]
After factory setting, it works!
