### ISSUE TITLE
Use Materials that can be converted to URP with the Render Pipeline Converter

### ISSUE THREAD

**Issue by Pepn** [oculus-samples/Unity-StarterSamples#9]
I think its safe to say most projects will use URP. However, the examples come in the default render pipeline which is okay -- if you could use the RenderPipeline Converter to convert everything. But this isn't the case a lot of materials (~90?) don't convert automatically.

**Comment by Abouzarpourranjbar** [comment]
Same issue here, specially the "ToyCubeWithOutline" shader is not working on URP

**Comment by AlexThiv** [comment]
Hi, we have this on track to release with the v67 release.

**Comment by AlexThiv** [comment]
@Pepn and @Abouzarpourranjbar we released v67 which address URP issues. If you encounter other issues you can open a new issue. Thanks for bringing this up.

**Comment by Abouzarpourranjbar** [comment]
Thanks guys
